"""Input guards applied at every trust boundary.

A pipeline specification is *configuration*, but in a large organisation it is
frequently authored by someone other than the platform owner and may be
generated by an upstream system.  It is therefore treated as untrusted input:

``resolve_within``
    Confines every filesystem path to an allow-listed root, defeating
    ``../../etc/shadow`` and symlink escapes.
``validate_url``
    Blocks SSRF: only ``http(s)``, no credentials in the URL, and by default no
    private/loopback/link-local address - including hosts that resolve to them,
    which is the DNS-rebinding-style bypass a naive hostname check misses.
``validate_identifier``
    SQL identifiers (table/column names) cannot be parameterised by the DB-API,
    so they must be validated against a strict pattern and quoted.  Values are
    always bound; identifiers are always validated.

These functions raise :class:`SecurityError` subclasses so a violation is
distinguishable from an ordinary configuration typo in metrics and alerts.
"""

from __future__ import annotations

import ipaddress
import re
import socket
from collections.abc import Iterable, Sequence
from pathlib import Path
from urllib.parse import urlparse, urlunparse

from ironflow.core.errors import ConfigurationError, SecurityError

#: Unquoted SQL identifiers: letter or underscore, then word characters.
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,62}$")
#: Optionally schema-qualified identifier.
_QUALIFIED_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,62}(\.[A-Za-z_][A-Za-z0-9_]{0,62})?$")

ALLOWED_URL_SCHEMES = frozenset({"http", "https"})

_DANGEROUS_SQL = re.compile(
    r"(;|--|/\*|\*/|\bunion\b|\bdrop\b|\bdelete\b|\btruncate\b|\bexec\b|\bxp_)",
    re.IGNORECASE,
)


# --------------------------------------------------------------------------- #
# Filesystem
# --------------------------------------------------------------------------- #
def resolve_within(
    path: str | Path, roots: Sequence[str | Path], *, must_exist: bool = False
) -> Path:
    """Resolve ``path`` and assert it stays inside one of ``roots``.

    ``Path.resolve`` collapses ``..`` *and* follows symlinks, so the comparison
    happens on the real target.  Checking the string before resolution - the
    common mistake - is bypassed by a symlink inside an allowed directory.

    An empty ``roots`` sequence means "unrestricted"; callers that handle
    untrusted paths must always pass a root.
    """
    candidate = Path(path).expanduser()
    resolved = candidate.resolve()

    if roots:
        allowed = [Path(r).expanduser().resolve() for r in roots]
        if not any(_is_relative_to(resolved, root) for root in allowed):
            raise SecurityError(
                "path escapes the configured data roots",
                context={"path": str(resolved), "roots": [str(r) for r in allowed]},
            )

    if must_exist and not resolved.exists():
        raise ConfigurationError("path does not exist", context={"path": str(resolved)})
    return resolved


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def safe_filename(name: str, *, fallback: str = "file") -> str:
    """Strip directory components and unsafe characters from a filename.

    Applied to names that arrive from remote systems (SFTP listings, HTTP
    ``Content-Disposition``) before they are joined to a local directory.
    """
    stem = Path(name).name
    cleaned = re.sub(r"[^A-Za-z0-9._-]", "_", stem).lstrip(".")
    return cleaned[:200] or fallback


# --------------------------------------------------------------------------- #
# Network
# --------------------------------------------------------------------------- #
def validate_url(
    url: str,
    *,
    allow_private: bool = False,
    allowed_hosts: Iterable[str] | None = None,
    allowed_schemes: Iterable[str] = ALLOWED_URL_SCHEMES,
) -> str:
    """Validate an outbound URL against the SSRF policy.

    Returns the URL with any embedded credentials removed - those belong in a
    header, not in a string that ends up in logs and proxy access records.
    """
    parsed = urlparse(url)
    schemes = {s.lower() for s in allowed_schemes}

    if parsed.scheme.lower() not in schemes:
        raise SecurityError(
            "URL scheme is not allowed",
            context={"scheme": parsed.scheme, "allowed": sorted(schemes)},
        )
    if not parsed.hostname:
        raise SecurityError("URL has no host", context={"url": url})

    host = parsed.hostname.lower()

    if allowed_hosts is not None:
        allow = {h.lower() for h in allowed_hosts}
        if host not in allow and not any(
            host.endswith(f".{suffix.lstrip('.')}") for suffix in allow
        ):
            raise SecurityError(
                "host is not in the connector allow-list",
                context={"host": host, "allowed": sorted(allow)},
            )

    if not allow_private:
        _assert_public_host(host)

    if parsed.username or parsed.password:
        netloc = parsed.hostname + (f":{parsed.port}" if parsed.port else "")
        return urlunparse(parsed._replace(netloc=netloc))
    return url


def _assert_public_host(host: str) -> None:
    """Reject hosts that resolve to a non-public address."""
    for address in _resolve_addresses(host):
        if (
            address.is_private
            or address.is_loopback
            or address.is_link_local
            or address.is_reserved
            or address.is_multicast
            or address.is_unspecified
        ):
            raise SecurityError(
                "URL resolves to a non-public address (SSRF guard)",
                context={"host": host, "address": str(address)},
            )


def _resolve_addresses(host: str) -> list[ipaddress.IPv4Address | ipaddress.IPv6Address]:
    """Resolve ``host`` to IP addresses, tolerating literals."""
    try:
        return [ipaddress.ip_address(host)]
    except ValueError:
        pass
    try:
        infos = socket.getaddrinfo(host, None, proto=socket.IPPROTO_TCP)
    except socket.gaierror as exc:
        raise SecurityError(
            "unable to resolve host for SSRF validation", context={"host": host}
        ) from exc
    resolved = []
    for info in infos:
        try:
            resolved.append(ipaddress.ip_address(info[4][0]))
        except ValueError:  # pragma: no cover - defensive
            continue
    if not resolved:  # pragma: no cover - getaddrinfo always yields something
        raise SecurityError("host did not resolve to any address", context={"host": host})
    return resolved


# --------------------------------------------------------------------------- #
# SQL
# --------------------------------------------------------------------------- #
def validate_identifier(name: str, *, kind: str = "identifier", qualified: bool = False) -> str:
    """Validate a SQL identifier that cannot be passed as a bind parameter."""
    pattern = _QUALIFIED_RE if qualified else _IDENTIFIER_RE
    if not isinstance(name, str) or not pattern.match(name):
        raise SecurityError(
            f"invalid SQL {kind}; expected an unquoted identifier",
            context={"kind": kind, "value": str(name)[:64]},
        )
    return name


def validate_identifiers(names: Iterable[str], *, kind: str = "column") -> list[str]:
    return [validate_identifier(n, kind=kind) for n in names]


def quote_identifier(name: str, *, dialect: str = "default") -> str:
    """Quote a *previously validated* identifier for the target dialect."""
    validate_identifier(name, qualified=False)
    if dialect == "mysql":
        return f"`{name}`"
    return f'"{name}"'


def assert_no_sql_injection(fragment: str, *, field: str = "expression") -> str:
    """Defence in depth for the few places a raw SQL fragment is accepted.

    Only reachable when an operator explicitly configures a custom ``where``
    clause; the primary defence is still that all *values* are bound.
    """
    if _DANGEROUS_SQL.search(fragment):
        raise SecurityError(
            "SQL fragment contains forbidden tokens",
            context={"field": field, "fragment": fragment[:120]},
        )
    return fragment


__all__ = [
    "ALLOWED_URL_SCHEMES",
    "assert_no_sql_injection",
    "quote_identifier",
    "resolve_within",
    "safe_filename",
    "validate_identifier",
    "validate_identifiers",
    "validate_url",
]
