"""Input guards applied at every trust boundary.

A pipeline specification is *configuration*, but in a large organisation it is
frequently authored by someone other than the platform owner and may be
generated by an upstream system.  It is therefore treated as untrusted input:

``resolve_within``
    Confines every filesystem path to an allow-listed root, defeating
    ``../../etc/shadow`` and symlink escapes.
``validate_url`` / :class:`NetworkPolicy`
    Blocks SSRF: only ``http(s)``, no credentials in the URL, and by default no
    private/loopback address - including hosts that *resolve* to one.  The
    policy belongs to the operator: a pipeline can narrow it, never widen it.
    Resolving a name here is only a pre-flight check; the address a connection
    actually uses is re-checked at connect time by
    :mod:`ironflow.security.net`, which is what closes DNS rebinding.
``validate_identifier``
    SQL identifiers (table/column names) cannot be parameterised by the DB-API,
    so they must be validated against a strict pattern and quoted.  Values are
    always bound; identifiers are always validated.

These functions raise :class:`SecurityError` subclasses so a violation is
distinguishable from an ordinary configuration typo in metrics and alerts.
"""

from __future__ import annotations

import ipaddress
import re
import socket
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Literal
from urllib.parse import urlparse, urlunparse

from ironflow.core.errors import ConfigurationError, SecurityError

#: Unquoted SQL identifiers: letter or underscore, then word characters.  Used
#: with ``fullmatch``: ``$`` alone also matches before a trailing newline, so
#: ``re.match`` let ``"orders\n"`` through.
_IDENTIFIER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]{0,62}")
#: Optionally schema-qualified identifier.
_QUALIFIED_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]{0,62}(\.[A-Za-z_][A-Za-z0-9_]{0,62})?")

ALLOWED_URL_SCHEMES = frozenset({"http", "https"})

#: Screen for the raw ``where`` option.  Statement stacking, comments and set
#: operations change the statement's shape; the verbs write or reach outside the
#: predicate; the functions sleep (a query-level denial of service) or read and
#: write files on the database server.
_DANGEROUS_SQL = re.compile(
    r"(;|--|#|/\*|\*/"
    r"|\b(?:union|intersect|except|drop|delete|truncate|insert|update|merge|alter|create"
    r"|grant|revoke|exec|execute|call|copy|attach|detach|pragma|into)\b"
    r"|\bxp_|\bsp_"
    r"|\b(?:pg_sleep|sleep|benchmark|waitfor|load_file|pg_read_file|pg_read_binary_file"
    r"|pg_ls_dir|lo_import|lo_export|dblink|outfile|dumpfile)\b)",
    re.IGNORECASE,
)

IPAddress = ipaddress.IPv4Address | ipaddress.IPv6Address


# --------------------------------------------------------------------------- #
# Filesystem
# --------------------------------------------------------------------------- #
def resolve_within(
    path: str | Path, roots: Sequence[str | Path], *, must_exist: bool = False
) -> Path:
    """Resolve ``path`` and assert it stays inside one of ``roots``.

    ``Path.resolve`` collapses ``..`` *and* follows symlinks, so the comparison
    happens on the real target.  Checking the string before resolution - the
    common mistake - is bypassed by a symlink inside an allowed directory.

    An empty ``roots`` sequence means "unrestricted"; callers that handle
    untrusted paths must always pass a root.
    """
    candidate = Path(path).expanduser()
    resolved = candidate.resolve()

    if roots:
        allowed = [Path(r).expanduser().resolve() for r in roots]
        if not any(_is_relative_to(resolved, root) for root in allowed):
            raise SecurityError(
                "path escapes the configured data roots",
                context={"path": str(resolved), "roots": [str(r) for r in allowed]},
            )

    if must_exist and not resolved.exists():
        raise ConfigurationError("path does not exist", context={"path": str(resolved)})
    return resolved


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def safe_filename(name: str, *, fallback: str = "file") -> str:
    """Strip directory components and unsafe characters from a filename.

    Applied to names that arrive from remote systems (SFTP listings, HTTP
    ``Content-Disposition``) before they are joined to a local directory.
    """
    stem = Path(name).name
    cleaned = re.sub(r"[^A-Za-z0-9._-]", "_", stem).lstrip(".")
    return cleaned[:200] or fallback


# --------------------------------------------------------------------------- #
# Network
# --------------------------------------------------------------------------- #
AddressKind = Literal["public", "private", "forbidden"]


def classify_address(address: IPAddress) -> AddressKind:
    """Sort an address into what the SSRF policy can do with it.

    ``forbidden`` is never reachable, whatever the operator allows: link-local
    is where cloud metadata services answer (``169.254.169.254``) and nothing an
    ETL job legitimately calls lives there; multicast and unspecified addresses
    are never an API.  ``private`` - loopback, RFC 1918, carrier-grade NAT,
    unique-local IPv6 and every other range IANA marks as not globally
    routable - is reachable only when the operator opens it.  Judging by
    ``is_global`` rather than a hand-written list is what catches ranges such
    as ``100.64.0.0/10`` that ``is_private`` does not cover.
    """
    if isinstance(address, ipaddress.IPv6Address) and address.ipv4_mapped is not None:
        address = address.ipv4_mapped  # ``::ffff:10.0.0.1`` is 10.0.0.1
    if address.is_loopback:
        return "private"  # a sidecar on the host can be allow-listed explicitly
    if address.is_link_local or address.is_multicast or address.is_unspecified:
        return "forbidden"
    return "public" if address.is_global else "private"


def host_matches(host: str, patterns: Iterable[str]) -> bool:
    """``example.com`` matches itself and every subdomain; nothing else."""
    candidate = host.lower().rstrip(".")
    for pattern in patterns:
        entry = pattern.strip().lower().rstrip(".").lstrip(".")
        if entry and (candidate == entry or candidate.endswith(f".{entry}")):
            return True
    return False


@dataclass(frozen=True)
class NetworkPolicy:
    """Where outbound HTTP may go.

    The operator decides it, in :class:`~ironflow.config.settings.Settings`,
    and a pipeline can only narrow it.  That asymmetry is the point: the
    pipeline file is the untrusted input, so an option in it that could switch
    the SSRF guard *off* - as a per-connector ``allow_private_network: true``
    once did, in production too - would make the guard decorative.

    * ``allow_private`` opens every non-public address except the forbidden
      ones.  Production refuses it.
    * ``private_hosts`` opens specific private destinations instead: host names
      (``internal-api.corp`` and its subdomains) or address ranges
      (``10.20.0.0/16``).  This is how an internal API is reached in production.
    * ``host_allowlists`` restrict *every* destination, public or not.  The
      operator's list (``IRONFLOW_HTTP_ALLOWED_HOSTS``) is what stops a pipeline
      from sending data or a credential to a host nobody approved; a
      connector's ``allowed_hosts`` narrows it further.
    """

    allow_private: bool = False
    private_hosts: tuple[str, ...] = ()
    host_allowlists: tuple[tuple[str, tuple[str, ...]], ...] = ()

    @classmethod
    def from_settings(cls, settings: Any) -> NetworkPolicy:
        allowed = tuple(settings.http_allowed_hosts)
        return cls(
            allow_private=bool(settings.allow_private_network),
            private_hosts=tuple(settings.http_private_hosts),
            host_allowlists=(("IRONFLOW_HTTP_ALLOWED_HOSTS", allowed),) if allowed else (),
        )

    def narrowed(
        self,
        *,
        allow_private: bool | None = None,
        allowed_hosts: Iterable[str] | None = None,
    ) -> NetworkPolicy:
        """This policy with a connector's restrictions applied on top.

        ``allow_private=False`` switches private addresses off; ``True`` leaves
        the operator's decision in place rather than overriding it.
        """
        allowlists = self.host_allowlists
        hosts = tuple(allowed_hosts or ())
        if hosts:
            allowlists = (*allowlists, ("connector", hosts))
        return replace(
            self,
            allow_private=self.allow_private and allow_private is not False,
            host_allowlists=allowlists,
        )

    def check_host(self, host: str) -> None:
        for label, hosts in self.host_allowlists:
            if not host_matches(host, hosts):
                raise SecurityError(
                    f"host is not in the {label} allow-list",
                    context={"host": host, "allowed": sorted(hosts)},
                )

    def check_address(self, host: str, address: IPAddress) -> None:
        kind = classify_address(address)
        if kind == "public":
            return
        if kind == "forbidden":
            raise SecurityError(
                "URL resolves to a non-public address that no setting opens (SSRF guard)",
                context={"host": host, "address": str(address)},
            )
        if self.allow_private or self._private_host_allowed(host, address):
            return
        raise SecurityError(
            "URL resolves to a non-public address (SSRF guard)",
            context={"host": host, "address": str(address)},
        )

    def resolve(self, host: str, port: int | None = None) -> list[str]:
        """Resolve ``host``; return the addresses a connection may use.

        One disallowed answer fails the whole lookup rather than being filtered
        out: a name that resolves to both a public and a private address is
        exactly what a rebinding attack serves.
        """
        self.check_host(host)
        addresses = _resolve_addresses(host, port)
        for address in addresses:
            self.check_address(host, address)
        return [str(address) for address in addresses]

    def _private_host_allowed(self, host: str, address: IPAddress) -> bool:
        if isinstance(address, ipaddress.IPv6Address) and address.ipv4_mapped is not None:
            address = address.ipv4_mapped
        for entry in self.private_hosts:
            try:
                network = ipaddress.ip_network(entry.strip(), strict=False)
            except ValueError:
                if host_matches(host, (entry,)):
                    return True
                continue
            if address.version == network.version and address in network:
                return True
        return False


def validate_url(
    url: str,
    *,
    allow_private: bool = False,
    allowed_hosts: Iterable[str] | None = None,
    allowed_schemes: Iterable[str] = ALLOWED_URL_SCHEMES,
    policy: NetworkPolicy | None = None,
) -> str:
    """Validate an outbound URL against the SSRF policy.

    ``policy`` carries the operator's rules; without one, ``allow_private``
    builds a minimal policy.  ``allowed_hosts`` narrows either.

    This is a pre-flight check with a readable error.  It resolves the name, but
    the connection itself resolves again, so on its own this cannot stop DNS
    rebinding - :mod:`ironflow.security.net` re-checks the address each
    connection actually uses.  With private addresses allowed, a *name* is not
    resolved here at all: the only answer left to refuse is a forbidden one,
    and the connect-time check sees that for free.

    Returns the URL with any embedded credentials removed - those belong in a
    header, not in a string that ends up in logs and proxy access records.
    """
    parsed = urlparse(url)
    schemes = {s.lower() for s in allowed_schemes}

    if parsed.scheme.lower() not in schemes:
        raise SecurityError(
            "URL scheme is not allowed",
            context={"scheme": parsed.scheme, "allowed": sorted(schemes)},
        )
    if not parsed.hostname:
        raise SecurityError("URL has no host", context={"url": url})

    host = parsed.hostname.lower()
    effective = (policy or NetworkPolicy(allow_private=allow_private)).narrowed(
        allowed_hosts=allowed_hosts
    )
    effective.check_host(host)

    if not effective.allow_private or _is_address_literal(host):
        for address in _resolve_addresses(host, parsed.port):
            effective.check_address(host, address)

    if parsed.username or parsed.password:
        netloc = parsed.hostname + (f":{parsed.port}" if parsed.port else "")
        return urlunparse(parsed._replace(netloc=netloc))
    return url


def _is_address_literal(host: str) -> bool:
    try:
        ipaddress.ip_address(host)
    except ValueError:
        return False
    return True


def _resolve_addresses(host: str, port: int | None = None) -> list[IPAddress]:
    """Resolve ``host`` to IP addresses, tolerating literals."""
    try:
        return [ipaddress.ip_address(host)]
    except ValueError:
        pass
    try:
        infos = socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)
    except (socket.gaierror, UnicodeError) as exc:
        raise SecurityError(
            "unable to resolve host for SSRF validation", context={"host": host}
        ) from exc
    resolved: list[IPAddress] = []
    for info in infos:
        try:
            address = ipaddress.ip_address(info[4][0])
        except ValueError:  # pragma: no cover - defensive
            continue
        if address not in resolved:
            resolved.append(address)
    if not resolved:  # pragma: no cover - getaddrinfo always yields something
        raise SecurityError("host did not resolve to any address", context={"host": host})
    return resolved


# --------------------------------------------------------------------------- #
# SQL
# --------------------------------------------------------------------------- #
def validate_identifier(name: str, *, kind: str = "identifier", qualified: bool = False) -> str:
    """Validate a SQL identifier that cannot be passed as a bind parameter."""
    pattern = _QUALIFIED_RE if qualified else _IDENTIFIER_RE
    if not isinstance(name, str) or not pattern.fullmatch(name):
        raise SecurityError(
            f"invalid SQL {kind}; expected an unquoted identifier",
            context={"kind": kind, "value": str(name)[:64]},
        )
    return name


def validate_identifiers(names: Iterable[str], *, kind: str = "column") -> list[str]:
    return [validate_identifier(n, kind=kind) for n in names]


def quote_identifier(name: str, *, dialect: str = "default") -> str:
    """Quote a *previously validated* identifier for the target dialect."""
    validate_identifier(name, qualified=False)
    if dialect == "mysql":
        return f"`{name}`"
    return f'"{name}"'


def assert_no_sql_injection(fragment: str, *, field: str = "expression") -> str:
    """Screen a raw ``where`` fragment.  Defence in depth, not the control.

    A predicate is SQL by definition, so no filter can make an arbitrary one
    safe: this rejects the shapes that turn a predicate into something else -
    a second statement, a comment that truncates the query, a set operation, a
    write, a time delay or a file read on the database server.  What actually
    bounds a ``where`` clause (and the fully raw ``query`` option) is that the
    connector's database account can only do what it was granted, and that
    every *value* is bound.
    """
    if _DANGEROUS_SQL.search(fragment):
        raise SecurityError(
            "SQL fragment contains forbidden tokens",
            context={"field": field, "fragment": fragment[:120]},
        )
    return fragment


__all__ = [
    "ALLOWED_URL_SCHEMES",
    "NetworkPolicy",
    "assert_no_sql_injection",
    "classify_address",
    "host_matches",
    "quote_identifier",
    "resolve_within",
    "safe_filename",
    "validate_identifier",
    "validate_identifiers",
    "validate_url",
]
